name: Node.js CI/CD
on:
  pull_request:
    branches:
      - main
    paths:
      - nodejs/**
      - .github/workflows/nodejs*.yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependency & run test
        run: |
          cd nodejs
          npm install
          npm test
